CONNECT TO NB1;

--PERFORM BINNING FOR AGE
UPDATE TEMPDATA SET ATT= 
(CASE
WHEN ATT>=15 AND ATT<25 THEN '15-25'
WHEN ATT>=25 AND ATT<35 THEN '25-35'
WHEN ATT>=35 AND ATT<45 THEN '35-45'
WHEN ATT>=45 AND ATT<55 THEN '45-55'
WHEN ATT>=55 THEN '>55'
END)
WHERE COLUMNNO = 21;

--PERFORM BINNING FOR CAMPAIGN
UPDATE TEMPDATA SET ATT= 
(CASE
WHEN ATT=1 THEN '1'
WHEN ATT=2 THEN '2'
WHEN ATT=3 THEN '3'
ELSE '>=4'
END)
WHERE COLUMNNO = 12;

--PERFORM BINNING FOR PDAYS
UPDATE TEMPDATA SET ATT= 
(CASE
WHEN ATT<5 THEN 'D1'
WHEN ATT>=5 AND ATT<25 THEN 'D2'
WHEN ATT=999 THEN 'D3'
END)
WHERE COLUMNNO = 13;

--PERFORM BINNING FOR EMP.VAR.RATE
UPDATE TEMPDATA SET ATT= 
(CASE
WHEN ATT<-2 THEN '1'
WHEN ATT>=-2 AND ATT<-1 THEN '2'
WHEN ATT>=-1 AND ATT<1 THEN '3'
WHEN ATT>=1 THEN '4'
END)
WHERE COLUMNNO = 16;

--PERFORM BINNING FOR NR.EMPLOYED
UPDATE TEMPDATA SET ATT= 
(CASE
WHEN ATT<=5000 THEN '1'
WHEN ATT>5000 AND ATT<=5100 THEN '2'
WHEN ATT>5100 AND ATT<=5200 THEN '3'
WHEN ATT>5200 THEN '4'
END)
WHERE COLUMNNO = 20;


CONNECT RESET;
TERMINATE;