
-- This script loads the data from an external file and stores it into a table.

CONNECT TO NB1;

--DROP TABLE BANK;
--DROP TABLE BANK1;

CREATE TABLE BANK("PID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , "AGE" INTEGER, "JOB" VARCHAR(100), "MSTATUS" VARCHAR(100), "EDUCATION" VARCHAR(100),"DEFAULT1" VARCHAR(100), "HOUSING" VARCHAR(100), "LOAN" VARCHAR(100), "CONTACT" VARCHAR(100), "MONTH1" VARCHAR(100), "DAY1" VARCHAR(100), "DURATION" INTEGER, "CAMPAIGN" INTEGER, "PDAYS" INTEGER, "PREVIOUS" INTEGER, "POUTCOME" VARCHAR(100), "ERATE" REAL, "CPIDX" REAL, "CCIDX" REAL, "EMR" REAL, "NEMP" REAL, "SUBSCRIBED" VARCHAR(100)); 


import FROM 'data\bank-additional.csv' OF del INSERT INTO BANK(AGE, JOB, MSTATUS, EDUCATION, DEFAULT1, HOUSING, LOAN, CONTACT, MONTH1, DAY1, DURATION, CAMPAIGN, PDAYS, PREVIOUS, POUTCOME, ERATE, CPIDX, CCIDX, EMR, NEMP, SUBSCRIBED);

CREATE TABLE BANK1("PID" INTEGER NOT NULL , "SUBSCRIBED" VARCHAR(100), "JOB" VARCHAR(100), "MSTATUS" VARCHAR(100), "EDUCATION" VARCHAR(100),"DEFAULT1" VARCHAR(100), "HOUSING" VARCHAR(100), "LOAN" VARCHAR(100), "CONTACT" VARCHAR(100), "MONTH1" VARCHAR(100), "DAY1" VARCHAR(100),"DURATION" INTEGER, "CAMPAIGN" INTEGER, "PDAYS" INTEGER, "PREVIOUS" INTEGER, "POUTCOME" VARCHAR(100), "ERATE" REAL, "CPIDX" REAL, "CCIDX" REAL, "EMR" REAL, "NEMP" REAL,"AGE" INTEGER); 

INSERT INTO BANK1 (SELECT PID, SUBSCRIBED, JOB, MSTATUS, EDUCATION, DEFAULT1, HOUSING, LOAN, CONTACT, MONTH1, DAY1, DURATION, CAMPAIGN, PDAYS, PREVIOUS, POUTCOME, ERATE, CPIDX, CCIDX, EMR, NEMP, AGE FROM BANK);

CONNECT RESET;
TERMINATE; 