
-- This script loads the data from an external file and stores it into a table. 

CONNECT TO NB1;

CREATE TABLE MUSHROOM("PID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) ,"EDIBILITY" VARCHAR(100), "CSHAPE" VARCHAR (100), "CSURFACE" VARCHAR (100), "CCOLOR" VARCHAR (100), "BRUISES" VARCHAR (100), "ODOUR" VARCHAR (100), "GATTACH" VARCHAR (100), "GSPACE" VARCHAR (100), "GSIZE" VARCHAR (100), "GCOLOR" VARCHAR (100), "SSHAPE" VARCHAR (100), "SROOT" VARCHAR (100), "SSABOVE" VARCHAR (100), "SSBELOW" VARCHAR (100), "SCABOVE" VARCHAR (100), "SCBELOW" VARCHAR (100), "VTYPE" VARCHAR (100), "VCOLOR" VARCHAR (100), "RNO" VARCHAR (100), "RTYPE" VARCHAR (100), "SPCOLOR" VARCHAR (100), "POPULATION" VARCHAR (100), "HABITAT" VARCHAR (100));



LOAD FROM 'data\agaricus-lepiota.data' OF del INSERT INTO MUSHROOM(EDIBILITY, CSHAPE, CSURFACE, CCOLOR, BRUISES, ODOUR, GATTACH, GSPACE, GSIZE, GCOLOR, SSHAPE, SROOT, SSABOVE, SSBELOW, SCABOVE, SCBELOW, VTYPE, VCOLOR, RNO, RTYPE, SPCOLOR, POPULATION, HABITAT);

CONNECT RESET ;
TERMINATE; 