CONNECT TO NB1~

-- drop tables 
--COUNTS FOR CLASS-ATT COMB
DROP TABLE NBC~ 
--CONTAINS PROB FOR CLASS-ATT COMB
DROP TABLE NBC_WT~ 
--COUNTS FOR EACH CLASS
DROP TABLE NBC_CLASS~ 
--SMOOTHENED COUNTS FOR EACH CLASS
DROP TABLE NBC_CLASSK~ 
 --ALL COMBINATION FOR CLASS-ATT
DROP TABLE COMB~

-- create the tables
--here probability is actually count
CREATE TABLE NBC("COL" INTEGER, "ATT" VARCHAR(100), "DECISION" VARCHAR(100), "PROBABILITY" INTEGER)~
--here probability is probability
CREATE TABLE NBC_WT("COL" INTEGER, "ATT" VARCHAR(100), "DECISION" VARCHAR(100), "PROBABILITY" DECIMAL(11,10))~
CREATE TABLE COMB("COL" INTEGER, "ATT" VARCHAR(100), "DECISION" VARCHAR(100), "PROBABILITY" INTEGER)~

CREATE TABLE NBC_CLASS("DECISION" VARCHAR(100), "PROBABILITY" INTEGER)~
CREATE TABLE NBC_CLASSK("DECISION" VARCHAR(100), "PROBABILITY" INTEGER)~

BEGIN ATOMIC
INSERT INTO NBC(COL, ATT, DECISION, PROBABILITY) 
	(SELECT COLUMNNO, ATT, DECISION, SUM(WEIGHT)
	 	FROM TRAIN_DATASET
		WHERE ISNUMERIC=0
		 GROUP BY (COLUMNNO, DECISION, ATT));
		 
INSERT INTO COMB
	WITH LABELS(DECISION) AS (SELECT DISTINCT DECISION FROM TEST_DATASET) 
	(SELECT DISTINCT COLUMNNO, ATT, LABELS.DECISION, 1
	FROM TEST_DATASET, LABELS WHERE ISNUMERIC=0);

UPDATE NBC SET PROBABILITY = PROBABILITY+1;

INSERT INTO NBC
	(SELECT * FROM COMB WHERE (COL,ATT,DECISION) 
	NOT IN (SELECT COL,ATT,DECISION FROM NBC));
			
INSERT INTO NBC_CLASS(DECISION, PROBABILITY)
		(SELECT DECISION, SUM(WEIGHT) FROM TRAIN_DATASET WHERE COLUMNNO = 1 GROUP BY DECISION);
		
INSERT INTO NBC_CLASSK(DECISION, PROBABILITY)
		(SELECT DECISION, PROBABILITY+1 FROM NBC_CLASS);
		
		
INSERT INTO NBC_WT
	(SELECT COL,ATT,N1.DECISION, CAST(N1.PROBABILITY AS DECIMAL(6,0)) / CAST(N2.PROBABILITY AS DECIMAL(6,0))
	FROM NBC AS N1,NBC_CLASSK AS N2 
	WHERE N1.DECISION = N2.DECISION);

END~
	
CONNECT RESET~
TERMINATE~	