CONNECT TO NB1;

-- drop tables 
DROP TABLE TEST_RESULTS;
DROP TABLE COMBINED_RESULTS;
DROP TABLE STATS;

-- create tables 
CREATE TABLE TEST_RESULTS("NUM" INTEGER DEFAULT 1, "COLUMN" INTEGER, "ACTUAL" VARCHAR(100), "PREDICTED" VARCHAR(100)); 

CREATE TABLE COMBINED_RESULTS("NUM" INTEGER DEFAULT 1, "ACCURACY" DECIMAL(11,10)); 

CREATE TABLE STATS("COLUMNNO" INTEGER, "MEAN" REAL, "VARIANCE" REAL, "DECISION" VARCHAR(100));

INSERT INTO STATS 
(SELECT COLUMNNO, AVG(ATT), VARIANCE(ATT), DECISION FROM TRAIN_DATASET WHERE ISNUMERIC=1 GROUP BY COLUMNNO, DECISION);

INSERT INTO TEST_RESULTS(COLUMN, ACTUAL, PREDICTED)
	WITH PROBABILITY(ROW, PREDICTED, PROB) AS
		((SELECT TEST_DATASET.PID, NBC_WT.DECISION, NBC_WT.PROBABILITY
			FROM TEST_DATASET, NBC_WT
			WHERE TEST_DATASET.COLUMNNO = NBC_WT.COL 
			AND TEST_DATASET.ATT = NBC_WT.ATT)
			UNION ALL
			(SELECT T.PID, S.DECISION, ((1/(SQRT(2*3.14*S.VARIANCE)))*(EXP(-POWER((T.ATT-S.MEAN),2)/(2*S.VARIANCE))))
			FROM TEST_DATASET T, STATS S
			WHERE T.COLUMNNO = S.COLUMNNO)
			),
		PROBABILITYSUM(ROW, PREDICTED, PROB) AS
		(SELECT ROW, PREDICTED, SUM(LOG(PROB)) FROM PROBABILITY GROUP BY ROW, PREDICTED),
		WEIGHTPROB(ROW, PREDICTED, PROB) AS
		(SELECT PROBABILITYSUM.ROW, PROBABILITYSUM.PREDICTED, PROBABILITYSUM.PROB + LOG(NBC_CLASS.PROBABILITY)
		FROM PROBABILITYSUM, NBC_CLASS
		WHERE PROBABILITYSUM.PREDICTED = NBC_CLASS.DECISION),
		MAXPROB(ROW, PROBABILITY) AS
		(SELECT ROW, MAX(PROB) FROM WEIGHTPROB GROUP BY ROW)
	(SELECT TD.PID, TD.DECISION, WP.PREDICTED
	FROM TEST_DATASET as TD, MAXPROB as MP, WEIGHTPROB AS WP
	WHERE TD.PID = MP.ROW 
	AND TD.PID = WP.ROW
	AND MP.PROBABILITY = WP.PROB
	AND TD.COLUMNNO = 1); 
	
INSERT INTO COMBINED_RESULTS(ACCURACY)
	WITH
		SUCCESS(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS WHERE PREDICTED = ACTUAL),
		TOTAL(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS)
		(SELECT CAST(SUCCESS.num AS DECIMAL(10,0))/CAST(TOTAL.num AS DECIMAL(10,0))
		FROM SUCCESS, TOTAL);
		
CONNECT RESET;
TERMINATE;