CONNECT TO NB1~

DROP TABLE TEST_DATASET~
DROP TABLE TRAIN_DATASET~

CREATE TABLE TEST_DATASET("PID" INTEGER, "COLUMNNO" INTEGER, "ATT" VARCHAR(100),"DECISION" VARCHAR(100), "ISNUMERIC" INTEGER, "WEIGHT" INTEGER)~
CREATE TABLE TRAIN_DATASET("PID" INTEGER, "COLUMNNO" INTEGER, "ATT" VARCHAR(100),"DECISION" VARCHAR(100), "ISNUMERIC" INTEGER, "WEIGHT" INTEGER)~

BEGIN ATOMIC
--UNCOMMENT BELOW LINE FOR MUSHROOM DATASET
	UPDATE TEMPDATA SET ISNUMERIC=1 WHERE COLUMNNO IN (11,17,18,19);
	
	
	FOR temp AS SELECT * FROM BANK1 ORDER BY PID DO  
	IF rand() > 0.80 THEN   
		INSERT INTO TEST_DATASET 
		(SELECT PID, COLUMNNO-1, ATT, DECISION, ISNUMERIC, WEIGHT
		FROM TEMPDATA WHERE PID=TEMP.PID);
	ELSE
		INSERT INTO TRAIN_DATASET 
		(SELECT PID, COLUMNNO-1, ATT, DECISION, ISNUMERIC, WEIGHT
		FROM TEMPDATA WHERE PID=TEMP.PID);
	END IF;
	END FOR;
END~


CONNECT RESET~
TERMINATE~