CONNECT TO NB1~

-- DROP TABLES IF THEY ALREADY EXIST

DROP TABLE TEMPDATA~
DROP TABLE TEMPLAB~

-- create the tables
CREATE TABLE TEMPDATA("PID" INTEGER, "COLUMNNO" INTEGER, "ATT" VARCHAR(100),"DECISION" VARCHAR(100), "ISNUMERIC"  INTEGER DEFAULT '0' NOT NULL, "WEIGHT" INTEGER)~

CREATE TABLE TEMPLAB("PID" INTEGER, "LABEL" VARCHAR(100))~

CREATE OR REPLACE PROCEDURE numColumns(IN TabName VARCHAR(100), OUT numcols INTEGER)
LANGUAGE SQL
BEGIN
	SET numcols = (	SELECT count(*)
			FROM   SYSIBM.SYSCOLUMNS
			WHERE  tbname = TabName );
END~
			
CREATE OR REPLACE PROCEDURE getColName(IN TabName VARCHAR(100), IN ColNum INTEGER, OUT ColName VARCHAR(100))
LANGUAGE SQL
BEGIN
	SET ColName = (	SELECT name
			FROM   SYSIBM.SYSCOLUMNS
			WHERE  tbname = TabName AND colno = ColNum );
END~

CREATE OR REPLACE PROCEDURE verticalize(IN TabName VARCHAR(100))
LANGUAGE SQL
BEGIN
	DECLARE TOTCOL INTEGER;
	DECLARE COLNO INTEGER;
	DECLARE COLNAME VARCHAR(100);
  	DECLARE STMT VARCHAR(200);
	
	CALL numColumns(TabName, TOTCOL);
	SET COLNO = 1;
    WHILE COLNO<TOTCOL
    DO
        CALL getColName(TabName, COLNO, COLNAME);
		IF COLNO=1 THEN
		SET STMT = 'INSERT INTO TEMPLAB '
                ||'SELECT M.PID, M.'||COLNAME||' FROM '||TabName||' M';
		ELSE
        SET STMT = 'INSERT INTO TEMPDATA '
                ||'SELECT M.PID, '||COLNO||', M.'||COLNAME||',T.LABEL'||', 0, 1 '
                ||' FROM '||TabName||' M, TEMPLAB T WHERE M.PID=T.PID';
		END IF;
        EXECUTE IMMEDIATE STMT;
        SET COLNO = COLNO + 1;
    END WHILE;
	
END~

CALL verticalize('BANK1');
--CALL verticalize('MUSHROOM');

CONNECT RESET~
TERMINATE~