CONNECT TO KNN~

DROP TABLE TEST_RESULTS~
DROP TABLE COMBINED_RESULTS~

CREATE TABLE TEST_RESULTS("ROWNO" INTEGER, "ACTUAL" VARCHAR(100), "PREDICTED" VARCHAR(100))~
CREATE TABLE COMBINED_RESULTS("NUM" INTEGER DEFAULT 1, "ACCURACY" DECIMAL(11,10))~

INSERT INTO TEST_RESULTS(ROWNO,ACTUAL,PREDICTED)
	WITH SQUARES(TESTID,TRAINID,SQ) AS
	(SELECT S.PID, R.PID, POWER(R.ATT-S.ATT,2)
	FROM TRAINDATA R, TESTDATA S
	WHERE R.COLUMNNO = S.COLUMNNO),
	
	DISTANCES(TESTID,TRAINID,DIST) AS
	(SELECT TESTID, TRAINID, SQRT(SUM(SQ))
	FROM SQUARES
	GROUP BY TESTID,TRAINID),
	
	TOP5(TESTID, TRAINID) AS
	(SELECT T.TESTID,T.TRAINID FROM (SELECT TESTID,TRAINID,RANK() OVER (PARTITION BY TESTID ORDER BY DIST) AS RANK FROM DISTANCES) T WHERE RANK<=5
	),

	TOPDECISIONS(TESTID, TRAINID, DECISION) AS
	(SELECT DISTINCT TESTID, TRAINID, DECISION FROM TOP5 T1,TRAINDATA T2 WHERE T1.TRAINID=T2.PID),

	MAJORITY(TESTID,CTR,PREDICTED) AS
	(SELECT TESTID, COUNT(DECISION), DECISION
	FROM TOPDECISIONS 
	GROUP BY TESTID,DECISION),

	PREDICTION(TESTID, PREDICTED) AS
	(SELECT TESTID,PREDICTED FROM (SELECT *,RANK() OVER (PARTITION BY TESTID ORDER BY CTR DESC) RNK FROM MAJORITY) WHERE RNK=1)

	(SELECT TESTID, LABEL, PREDICTED 
	FROM PREDICTION,TESTLAB
	WHERE TESTID=PID)~

INSERT INTO COMBINED_RESULTS(ACCURACY)
	WITH
		SUCCESS(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS WHERE PREDICTED = ACTUAL),
		TOTAL(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS)
		(SELECT CAST(SUCCESS.num AS DECIMAL(10,0))/CAST(TOTAL.num AS DECIMAL(10,0))
		FROM SUCCESS, TOTAL)~

CONNECT RESET~
TERMINATE~
