---- INITIALIZATION ----

CONNECT TO KNN~

-- drop the tables we're about to create, in case they already exist

DROP TABLE TRAINDATA~
DROP TABLE TRAINLAB~
DROP TABLE TESTDATA~
DROP TABLE TESTLAB~

-- create the tables
CREATE TABLE TRAINDATA("PID" INTEGER, "COLUMNNO" INTEGER, "ATT" VARCHAR(100),"DECISION" VARCHAR(100), "WEIGHT" INTEGER)~
CREATE TABLE TRAINLAB("PID" INTEGER, "LABEL" VARCHAR(100))~
CREATE TABLE TESTDATA("PID" INTEGER, "COLUMNNO" INTEGER, "ATT" VARCHAR(100),"DECISION" VARCHAR(100), "WEIGHT" INTEGER)~
CREATE TABLE TESTLAB("PID" INTEGER, "LABEL" VARCHAR(100))~

CREATE OR REPLACE PROCEDURE numColumns(IN TabName VARCHAR(100), OUT numcols INTEGER)
LANGUAGE SQL
BEGIN
	SET numcols = (	SELECT count(*)
			FROM   SYSIBM.SYSCOLUMNS
			WHERE  tbname = TabName );
END~
			
CREATE OR REPLACE PROCEDURE getColName(IN TabName VARCHAR(100), IN ColNum INTEGER, OUT ColName VARCHAR(100))
LANGUAGE SQL
BEGIN
	SET ColName = (	SELECT name
			FROM   SYSIBM.SYSCOLUMNS
			WHERE  tbname = TabName AND colno = ColNum );
END~

CREATE OR REPLACE PROCEDURE verticalize(IN TabName VARCHAR(100), IN Tdata VARCHAR(100), IN Tlab VARCHAR(100))
LANGUAGE SQL
BEGIN
	DECLARE TOTCOL INTEGER;
	DECLARE COLNO INTEGER;
	DECLARE COLNAME VARCHAR(100);
  	DECLARE STMT VARCHAR(200);
	
	CALL numColumns(TabName, TOTCOL);
	SET COLNO = TOTCOL-1;
    WHILE COLNO>0
    DO
        CALL getColName(TabName, COLNO, COLNAME);
		IF COLNO=TOTCOL-1 THEN
		SET STMT = 'INSERT INTO '||Tlab
                ||' SELECT M.PID, M.'||COLNAME||' FROM '||TabName||' M';
		ELSE
        SET STMT = 'INSERT INTO '||Tdata
                ||' SELECT M.PID, '||COLNO||', M.'||COLNAME||',T.LABEL'||', 1 '
                ||' FROM '||TabName||' M, '||Tlab||' T WHERE M.PID=T.PID';
		END IF;
        EXECUTE IMMEDIATE STMT;
        SET COLNO = COLNO - 1;
    END WHILE;
	
END~

CALL verticalize('HVTRAIN','TRAINDATA','TRAINLAB')~
CALL verticalize('HVTEST','TESTDATA','TESTLAB')~

CONNECT RESET~
TERMINATE~